import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import { ClerkProvider } from '@clerk/nextjs'
import { dark,neobrutalism } from '@clerk/themes';
// import  Providers from "../../store/provider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider 
    appearance={{
      baseTheme: dark
      
    }}>
      <html lang="en">
        {/* <Providers> */}
        <body className={`${inter.className} bg-cover bg-center bg-fixed`}>
          {children}
        </body>
        {/* </Providers> */}
      </html>
    </ClerkProvider>
  );
}